name: WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Generate Wakatime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: "▱▰"
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SYMBOL_VERSION: 2
          LANG_COUNT: 5
          COMMIT_MESSAGE: "chore: update waka time stats 📊"
          TIME_RANGE: "all_time"
          TIMEZONE: "Europa/Istanbul"
